C
C     Definition von COMMON - Bloecken  fuer CASOUT, DENSTY, ENGOUT,
C     EVA, GRIDS, HIVAP, POPUL, ROWOUT, SEQIN, SEQOUT
C     Stand: 2.5. 1994
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMMON POP(4096),POPN(4096),POPP(4096),POPA(4096),EXMAX1,EXMAX2,
     &       EXMAX3,EXMAX4,OMEGG(2500),OMEGN(2500),OMEGP(2500),
     &       OMEGA(5000),OMEGF(2500),EXMAXG,EXMING,EXMAXN,EXMINN,EXMAXP,
     &       EXMINP,EXMAXA,EXMINA,EXMAXF,EXMINF,TZERO,SPECJ(300),Q(5),
     &       AL(5),R(5),DELTA(5),P(5),HIST(5),TOTAL(25),SIG(25),
     &       SIGNN(25),SIGP(25),SIGA(25),TRIM(25),RP(25),RLOSTG(25),
     &       RLOSTN(25),RLOSTP(25),RLOSTA(25),RLOSTF(25),AVGJ(25),
     &       TITLE(20),ELAB,EXCIT,ACN,ZCN,FLOST(25),TSPECG(26),
     &       TSPECQ(26),TSPECN(26),TSPECP(26),TSPECA(50),TSPECF(26),
     &       TMTBG(130),TMTBN(598),TMTBP(598),TMTBA(1950),CUT,PRCNT,
     &       SPECG(26),SPECQ(26),SPECN(26),SPECP(46),SPECA(80),
     &       SPECF(20),SUMLOW,AVGF,QC,FLAND(300),STRIPE,SHELLS(27,27),
     &       ESHELL,SHELK(5),TABLE(4096),ALS(27,27),DELTAS(27,27),
     &       SPECE(400),AVGE(25),AVGJF(25),AVGEF(25),DJN(25),DJP(25),
     &       DJA(41),DJ(5),SSP(5),AVESP(5),YFISJ(300),ELAB1,EXCIT1,
     &       SUMEG(25),SUMJG(25),IPOPS,M1,N1,M2,N2,M3,N3,M4,N4,IDEN,
     &       IDNA,MWG,NWG,MWN,NWN,MWP,NWP,MWA,NWA,MWF,NWF,LADJ(5),
     &       NZUP,NAUP,KZ(25),IN(25),IND(25),NZ,NZ1,NA,IZT,MTGT,IZP,
     &       MPROJ,IGROG,IOUT,NON,NOP,NOA,NOG,NOF,NOE2,IU1,IU2,ITEST,
     &       ICUT,ISEQ(25),KEA1,KEP1,JFJI,LGD,MAXG,MAXN,MAXP,MAXA,MAXF,
     &       KEF,IOPT,ITG,ITN,ITP,ITA,ISHELL,IPAIR,ISHELF,LPRINT,IEDIM,
     &       IAMX,JFIS
      CHARACTER*1 TABLE
      COMMON/ROW/XSECT(27,27),SIGZ(27),SIGFUS,SIGEVA,SIGFIS,FLGRAZ
      COMMON/YR/EJAY(1500),RATIOS(6),RATIOF(6),FINERT,FINERF,
     &          JDIM,JUPYR,IYR,IRAST,INERF,NOROTF
      COMMON/BARR/BFLDM(25,25),BFS(25,25),BAR0,BARFAC,IBF,IFISRT
      COMMON/GAM/ECUBE(26),EFIVE(26),CGIANT,EGIANT,GAMMA,GAMQ,KEG,JFACTR
      COMMON/BIND/BE(25,25,5),EXC(27,27),DELT,MC,MP,NUMB,MASSES
      COMMON/TRNS/TCOFN(25,13),TCOFP(25,13),TCOFA(50,21),DEL(5),
     1            KEN,KEP,KEA,LN,LP,LA,IOVER
      COMMON/TLJ/TTT(160)
      COMMON/FISRT/ROT0,A2MS,RKAPPA,X0,Y0,RKAPA4
      COMMON/ELEM/ELEMNT(128)/S/BLANK,SYMB(7),NU(15)
      PARAMETER (NENMX=16)
      COMMON/CASE/XSECTE(27,27,NENMX),ELABE(NENMX),SIGFUE(NENMX),
     1            SIGEVE(NENMX),
     2            SIGFIE(NENMX),FLGRAE(NENMX),ELABE1(NENMX),NEXC
      COMMON/POPU/DJJ2,DJJ3,DJJ4,YPOPJ(300),YERJ(300),YFISS(300),
     &            PER(300),PFIS(300),JFMINN,JFMINP,JFMINA
      COMMON/ROW1/AVDJN(25),AVDJP(25),AVDJA(25),EAVN(25),EAVP(25),
     1            EAVA(25),IME(25)
      COMMON/ISOM/SIGISO(0:5),NUMISO,ISO,ISOA(0:5),ISOZ(0:5),ISOJ(0:5)
      COMMON/DNS/YRSMO(1500),EDCOLL,AX,UCRIT,BETA0,
     1           IENH,IPREEX,ENHANC(400),ENHANS(400)
      COMMON/BEES/BS,BC,BK,BR,BV,BW
      COMMON/PGAMMA/PENTRY(4096)
      COMMON/POTS/ VRN,R0RN,ADIFRN,VIN,R0IN,ADIFIN,
     1             VRP,R0RP,ADIFRP,VIP,R0IP,ADIFIP,RCLMBP,CBFACP,
     2             VRA,R0RA,ADIFRA,VIA,R0IA,ADIFIA,RCLMBA,CBFACA,QQ2
      COMMON/SPECT/SPECGT(26),SPECQT(26),SPECNT(26),SPECPT(46),
     1              SPECAT(80),SPECFT(20)
      COMMON/FUS/VBFUS,RBFUS,HWFUS
      CHARACTER*1   BLANK,NU,SYMB
      CHARACTER*4   ELEMNT,TITLE
      DIMENSION SIGF(25),STORE(27,27)
      EQUIVALENCE (RLOSTF(1),SIGF(1)),(STORE(1,1),EXC(1,1))
C-----------------------------------------------------------------------
C     This file is included into program units; do not terminate them here.
