      SUBROUTINE FUSION(ELAB,AP,ZP,AT,ZT,QQ,V0,R00,D,XTH,APUSH,FPUSH,
     1                   CRED,NORUTH,
     2             NOPROX,NOCURV,ION,SIGML,FLGRAZ,LMAX,SIGF,ITEST,IOPT)
C
C  Berechnet Fusionsquerschnitte nach der WKB-Methode fuer verschiedene
C  Kern-Kern-Potentiale, erlaubt deformierte Target-Kerne und
C  erhoehte Sub-Barrieren - Transparenz
C  ruft VLRO(Eingaenge V0, VL, VR), TWKB(Eingang WKB), PARABO, FISROT
C  auf; maechtigere Version FUSIO wurde entwickelt
C  Modifikation 8.10.1987
C  Modifikation 7.6.1994 Drehimpulsbegrenzung von BAR>0.5 auf
C  BAR>0.1 gesenkt, da vorher LCRIT = 1 fuer Z_CN > 105
C  Stand: 7.6.1994
C
      IMPLICIT REAL*8 (A-H,O-Z)
      COMMON/FUS/VBFUS,RBFUS,HWFUS
C--------------------------------------------------------------------
C     VERSION OF FUSION ALLOWING TO COMMUNICATE BARRIER PARAMETERS
C--------------------------------------------------------------------
C     24 PARAMETRS
C     AP PROJECTILE MASS (SPHERIC)
C     AT TARGET MASS (DEFORMED)
C     ZP PROJECTILE Z  (SPHERIC)
C     ZT TARGET(DEFORMED) Z
C     QQ  ALIAS Q2 :QUADRUPOLE MOMENT OF TARGET IN (FM**2)
C     V0,R00,D : POT PARAMETRES
C     FOR MASSES 1,2,3: RPS+RTS=R00*AT3
C     FOR MASS   4    : RPS+RTS=R00*AT3+1.6
C     FOR MASSES >4   : RPS+RTS=R00*(AT3 + AP3)
C     XTH,APUSH,FPUSH:PARAMETERS,XTH,A,F OF BJORNHOM-SWIATECKI 82 EXTRAP
C     CRED : ALLOWS TO MANIPULATE BARRIER TRANSPARENCY,USUALLY=1
C            IN PARABOLIC APPROX CRED IS PROPORT TO 1./SQRT(OMEGA)
C     NORUTH =1:DOES NOT USE CHANGE OF ORIENTATION ANGLE ALONG TRAJ.
C     NORUTH =2:SAME AS 1,BUT ALSO DOES NOT USE QUADRATIC COULOMB INSIDE
C     NOPROX =1:USES CENTER LINE PRESCRIPTION(INSTEAD OF PROX.PRESCR.)
C     NOCURV =1:IGNORES CURVATURE DEPENDANCE OF POT
C     LMAX   INPUT:  -1   MAXIMUM L WILL BE DETERMINED FROM
C                         BFLDM(L)<0.5 MEV (NEEDS FISROT)
C                    <-1  MAXIMUM L CALCULATED IS |LMAX|
C                    >=0  MAXIMUM L IS DETERMINED INTERNALLY
C             OUTPUT      MAXIMUM L CALCULATED
C     SIGF    OUTPUT: FUSION CROSS SECTION IN MB
C     ITEST :IS SET 99 IF POT HAS NO POCKET FOR L=0
C            2,3,4,5    BIG PRINT OUT
C            1          SMALL PRINT OUT
C            <1  OR >5  NOPRINT OUT
C            3 OR -1    PARABOLIC APPROX.(RATHER THAN WKB)
C            -2         CLASSICAL APPROX.(NO TUNNELLING)
C     IOPT =-2:SAME AS -1 BUT FOR AP=1 SPIN ORBIT L+1/2 IS ADDED
C     IOPT =-1:NUCLEAR IS WS,NO RADII CORRECTION,USE CENTRAL RADII
C          =0:VNUCLEAR IS EXPONENTIAL,NO RADII CORRECTION,CENTRAL RADII
C          =1:VNUCLEAR IS EXPONENTIAL,WITH RADII CORRECTION,SHARP RADII
C          =2:FULL PROXIMITY POT,WITH RADII CORRECTION,USE SHARP RADII
C          =3:FULL PROXIMITY POT,NO RADII CORRECTION,USE CENTRAL RADII
C          =4: EXP PROXIMITY POT,WITH RADII CORRECTION,USE SHARP RADII
C          =5: BASS POTENTIAL,BERLIN 79, SET V0,R0,D=0.
C     ION  =1: 5 POINT ORIENTATIONAL INTEGRATION
C          =2:10 POINT ORIENTATIONAL INTEGRATION
C          =3:OCOS=0  OR THETA=90 DEGREE
C          =4:OCOS=1  OR THETA= 0 DEGREE
C------------------------------------------------------------------
      DIMENSION Z(17),WEIGHT(17),X(3),Y(3),A1(3),SIGML(1),RMX(17),
     1 T0(17),VMX(17),TMX(17),HWMX(17),IWKB(17),RINN(17),ROUTT(17)
     2 ,TPARAP(17),SIGOR(17)
      COMMON/FISRT/ROT0,A2MS,RKAPPA,X0,Y0
      DATA WEIGHT/.23693,.47863,.56889,.47863,.23693,.06667,.14945,
     1 .21909,.26927,.29552,.29552,.26927,.21909,.14945,.06667,2.0,2.0/,
     2 Z/.04691,.23077,.50000,.76923,.95309,.01305,.06747,.16030,.28330,
     3 .42556,.57444,.71670,.83397,.93253,.98693,0.,1./,
     4 HBARC,AMU/197.329,931.502/

      AMPAR1=0.2
      AMPAR2=0.02
      LUP=200
      AMXEXP=100.
      TMIN=EXP(-AMXEXP)
C-----------------------------------------S1--------------------------
      R0FUS=0.
      Q2=QQ
      NOWKB=0
      ICLASS=0
      IF(ITEST.EQ.3)NOWKB=1
      IF(ITEST.EQ.-1 .OR. ITEST.EQ. -2) NOWKB=1
      IF(ITEST.EQ.-2) ICLASS=1
      LIMBAR=0
      IF(LMAX.EQ.(-1))LIMBAR=1
      IF(LMAX.LT.-1)LUP=IABS(LMAX)
      DO 5 L=1,LUP
 5    SIGML(L)=0.
      DO 6 IO=1,17
      SIGOR(IO)=0.
 6    ROUTT(IO)=0.
      ARED=AP*AT/(AP+AT)
      ECM=ELAB*AT/(AP+AT)
      IF(ITEST.GT.0 .AND. ITEST.LT.6)WRITE(6,10) ELAB,ECM
 10   FORMAT(' FUSION ELAB=',F8.1,4X,'ECM=',F8.1)
      HW0=HBARC*HBARC/(AMU*ARED)
      SIG0=15.708*HW0/ECM
      ACN=AP+AT
      ZCN=ZP+ZT
      AN=ACN-ZCN
      MPNT=5
      MTIMES=1
      F0=2./HW0
C     LIMBAR=0
      ONLYGS=0.
C--------------------------------------   S2
      K=MAX0(ION,1)
      K=MIN0(ION,4)
      IF(ABS(Q2).LT.0.01) K=4
      GOTO(30,32,34,36),K
 30   IO1=1
      IO2=5
      GOTO 38
 32   IO1=6
      IO2=15
      GOTO 38
 34   IO1=16
      IO2=16
      GOTO 38
 36   IO1=17
      IO2=17
C---------------------------------------  S3
 38   AP3=AP**0.333333
      AT3=AT**0.333333
      IO=IO1
      SUM=0.
      SUMCL=0.
      L=0
      IF(ZP.LE.0.)L=1
      R0=R00
      IF(R0.GT.0.) GOTO 50
      RPS=1.28*AP3-0.76+0.8/AP3
      RTS=1.28*AT3-0.76+0.8/AT3
      IF(IOPT.EQ.1 .OR. IOPT.EQ.2  .OR. IOPT.EQ.4 .OR. IOPT.EQ.5)
     1               GOTO 40
C     VLRO NEEDS SHARP RADII FOR OPTIONS 1,2,4,5(BASS)
      RPS=RPS-1./RPS
      RTS=RTS-1./RTS
C     VLRO NEEDS CENTRAL RADII FOR OPTIONS -1(WS),0(EXP), AND 3(PROX)
 40   R0=(RPS+RTS)/(AP3+AT3)
 50   IF(AP.LT.3.01)R0=R00*AT3/(AT3+AP3)
      RPS=R0*AP3
      RTS=R0*AT3
      IF(AP.LT.4.01 .AND. AP.GT.3.99)RPS=1.6
      R=RPS+RTS
      RPTS=R
      RFUS=R0FUS*R/R0
      OCOS=Z(IO)
      V=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      DR=0.2
      DR2=0.1
      RUP=50.*DR+R
      R=R+DR
      V1=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      IUP=50
      DO 60 I=1,IUP
      R=R+DR
      V2=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      IF(V2.LT.V1 .AND.V.LT.V1) GOTO 70
      V=V1
      V1=V2
 60   CONTINUE
 62   SIGF=0.
      LMAX=0
      WRITE(6,64) OCOS
 64   FORMAT(' FUSION: POTENTIAL FOR L=0 HAS NO POCKET COS=',F8.3)
      WRITE(6,66) AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,
     1      OCOS, V0,R0,D,ECM,L,R,IOPT
 66   FORMAT(4F6.0,F8.1,3I4/4F8.3,F8.1,I4,F8.2,I4)
      ITEST=99
      RETURN
 70   X(3)=R
      Y(3)=V2
      X(2)=R-DR
      Y(2)=V1
      X(1)=X(2)-DR
      Y(1)=V
      IREP=0
 71   CALL PARABO(X,Y,A1,RMAX,VLB)
      VBFUS=VLB
      RBFUS=RMAX
      IF(IREP.EQ.1) GOTO 72
      X(3)=RMAX+0.15
      Y(3)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,X(3),IOPT)
      X(2)=RMAX
      Y(2)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,RMAX,IOPT)
      X(1)=RMAX-0.15
      Y(1)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,X(1),IOPT)
      IREP=1
      GOTO 71
 72   D2VLB=2. *A1(3)
      HW=HW0*ABS(D2VLB)
      HW=SQRT(HW)
      HWFUS=HW
      HWMX(IO)=HW
      VMX(IO)=VLB
      RMX(IO)=RMAX
      DUM=       6.28319*(VLB-ECM)/HW
      IF(ECM.LT.VLB)DUM=DUM*SQRT(CRED)
      IF(ABS(DUM).LT.AMXEXP)T0(IO)=1./(1.+EXP(DUM))
      IF(DUM.GT.AMXEXP)T0(IO)=0.
      IF(DUM.LT.(-AMXEXP))T0(IO)=1.
      TPARAP(IO)=T0(IO)
      IF(NOWKB.EQ.1) GOTO 74
      IWKB(IO)=0
      IF(T0(IO).GT.0.49) GOTO 74
      IWKB(IO)=1
      IF(T0(IO).EQ.0.) GOTO 74
      RIN=RMAX
      ROUT=1.44*ZP*ZT/ECM-2.
      IF(ZP.LE.0.)ROUT=SQRT(HW0/ECM)-3.
      ROUT=DMAX1(RMAX,ROUT)
      DR=0.1
      DUM =TWKB(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,V0,R0,D,XTH,APUSH,
     1          FPUSH,DR,OCOS,ECM,L,RIN,ROUT,RFUS,CRED,IOPT)
      T0(IO)=0.
      IF(DUM.LE.0.)GOTO 73
      T0(IO)=1./(1.+(1./DUM))
 73   RINN(IO)=RIN
      ROUTT(IO)=ROUT
      IF(ITEST.GT.1 .AND.ITEST.LT.6)
     1WRITE(6,7300) ECM,OCOS,RMAX,RPTS,RIN,ROUT,RFUS
 7300 FORMAT(' WKB L=0:ECM,OCOS,RMAX,RPTS,RIN,ROUT,RFUS',7F9.3)
 74   IF(ICLASS.EQ.0) GOTO 75
      IF(T0(IO).GE.0.5) TCL=1.
      IF(T0(IO).LT.0.5) TCL=0.
      SUMCL= SUMCL+WEIGHT(IO)*TCL
 75   SUM=SUM+WEIGHT(IO)*T0(IO)
 7500 IF(IO.GE.IO2) GOTO 90
      IO=IO+1
      OCOS=Z(IO)
C--------------------------------------
      IF(Q2.LT.0) GOTO 80
      R=RMX(IO-1)-DR2
      V=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R+DR
      V1=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R+DR
      V2=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
 76   IF(V2.LT.V1 .AND. V.LT.V1)GOTO 70
      V=V1
      V1=V2
      R=R+DR
      IF(R.GT.RUP) GOTO 62
      V2=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      GOTO 76
 80   R=RMX(IO-1)+DR2
      V2=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R-DR
      V1=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R-DR
      V=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
 86   IF(V2.LT.V1 .AND. V.LT.V1) GOTO 88
      V2=V1
      V1=V
      R=R-DR
      IF(R.LT.RPS) GOTO 62
      V=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      GOTO 86
 88   R=R+DR+DR
      GOTO 70
C-------------------------------------
 90   T=SUM*0.5
      TCL=SUMCL*0.5
      T00=0.01*T
      IF(ITEST.LT.2) GOTO 105
      IF(IO2.GT.15) GOTO 95
      WRITE(6,101) T,L
      WRITE(6,100) (VMX(IO),IO=IO1,IO2),(RMX(IO),IO=IO1,IO2),
     1             (HWMX(IO),IO=IO1,IO2)
      WRITE(6,103) (T0(IO),IO=IO1,IO2)
      WRITE(6,103) (TPARAP(IO),IO=IO1,IO2)
      DO 92 IO=IO1,IO2
 92   SIGOR(IO)=SIG0*T0(IO)
      GOTO 105
 95   WRITE(6,102) VMX(IO),RMX(IO),HW,T,L
 100  FORMAT(5F12.2)
 103  FORMAT(5E12.3)
 101  FORMAT( E12.3,I4)
 102  FORMAT(3F12.3,E12.3,I4)
C----------------------------------------------
 105  IFLAG=0
      SIGML(1)=SIG0*T
      IF(ICLASS.EQ.1) SIGML(1)=SIG0*TCL
      IF(ZP.GT.0.)GOTO 106
      TN=1.-EXP(-1.085*SQRT(ECM))
      IF(ITEST.GT.1 .AND. ITEST.LT.6) WRITE(6,107) ECM,TN
 107  FORMAT( ' ECM,T0',F8.2,E12.3)
      SIGML(1)=SIG0*TN
 106  SIGF=SIGML(1)
C     IF(SIGF.LT..1E-6)GOTO 400
      T=1.
      DO 110 IO=IO1,IO2
      TMX(IO)=T0(IO)
 110  T0(IO)=0.01*T0(IO)
C----------------------------------------PARTIAL WAVE LOOP L
      DO 250 L=1,LUP
      AL=L
      IF(LIMBAR.EQ.0) GOTO 120
      CALL FISROT(ACN,ZCN,AN,AL,DELR,DELSP,ERO,ONLYGS)
      BAR=DELSP-DELR
      IF(BAR.GT.0.1) GOTO 120
      FLGRAZ=AL
      IFLAG=2
      GOTO 260
 120  T1=T
      SUM=0.
      SUMCL=0.
C------------------------------------ORIENTATION LOOP IO
      DO 150 IO=IO1,IO2
      IF(TMX(IO).LT.TMIN) GOTO 125
      IF(LUP.LT.200) GOTO 130
      IF(TMX(IO).GT.T0(IO)) GOTO 130
 125  TMX(IO)=0.
      GOTO 150
 130  OCOS=Z(IO)
      R=RMX(IO)
      X(2)=R
      Y(2)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R+0.15
      X(3)=R
      Y(3)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      R=R-0.30
 132  X(1)=R
      Y(1)=VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0,D,
     1       XTH,APUSH,FPUSH,ECM,L,R,IOPT)
      CALL PARABO(X,Y,A1,RMAX,VLB)
      IF(RMAX.GT.X(3))GOTO 135
      IF(RMAX.GT.X(1))GOTO 134
      X(3)=X(2)
      Y(3)=Y(2)
      X(2)=X(1)
      Y(2)=Y(1)
      R=R-0.15
      IF(R.LT.R12) GOTO 135
      GOTO 132
 134  D2VLB= 2.*A1(3)
      HW=HW0*ABS(D2VLB)
      HW=SQRT(HW)
      IF(A1(3).GT.0.) GOTO 135
      DUM=       6.28319*(VLB-ECM)/HW
      IF(ECM.LT.VLB)DUM=DUM*SQRT(CRED)
      IF(ABS(DUM).LT.AMXEXP)T =1./(1.+EXP(DUM))
      IF(DUM.GT.AMXEXP)T =0.
      IF(DUM.LT.(-AMXEXP))T =1.
      JWKB=0
      GOTO 136
 135  T=0.
      IF(ITEST.GT.1 .AND. ITEST.LT.6) WRITE(6,1350) OCOS,L
 1350 FORMAT(' OCOS,L=',F8.3,I4,4X,'PROBABLY NO POCKET')
 136  RMX(IO)=RMAX
      VMX(IO)=VLB
      TPARAP(IO)=0.
      IF(T.LE.0.)GOTO 145
      TPARAP(IO)=T
      IF(NOWKB.EQ.1) GOTO 145
      IF(T.GT.0.49) GOTO 145
      IF(T.EQ.0.) GOTO 145
C---------------------------
      IF(ROUTT(IO).LE.0.) GOTO 138
      IF(RINN (IO).LE.0.) GOTO 138
      DUM=(ROUTT(IO)-RINN(IO))*0.1
      DR=DMIN1(AMPAR1,DUM)
      DR=DMAX1(AMPAR2,DR)
      RIN=RINN(IO)+DR
      RIN=DMIN1(RMX(IO),RIN)
      ROUT=ROUTT(IO)-DR
      ROUT=DMAX1(ROUT,RMX(IO))
      GOTO 139
 138  RIN=          RMX(IO)
      ROUT=RIN
      DR=0.1
 139  IF(ZP.GT.0.) GOTO 140
      ROUT=SQRT(HW0*L*(L+1)/(2.*ECM))-0.5
 140  IF(R0FUS.LE.0.)RFUS=-RINN(IO)
         T=TWKB(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,V0,R0,D,XTH,APUSH,
     1          FPUSH,DR,OCOS,ECM,L,RIN,ROUT,RFUS,CRED,IOPT)
      IF(T.GT.0.)T=1./(1.+(1./T))
      IF(T.LE.0.0 .AND. TPARAP(IO).GT.0.05) T=TPARAP(IO)
      RINN(IO)=RIN
      ROUTT(IO)=ROUT
      JWKB=1
      IWKB(IO)=1.
 145  IF(ICLASS.EQ.0) GOTO 146
      IF(T.GE.0.5) TCL=1.
      IF(T.LT.0.5) TCL=0.
      SUMCL= SUMCL+WEIGHT(IO)*TCL
 146  TMX(IO)=T
      HWMX(IO)=HW
      SUM=SUM+WEIGHT(IO)*T
 150  CONTINUE
C--------------------------------------- END ORIENTATION LOOP IO
      L1=L+1
      T=SUM*0.5
      TCL=SUMCL*0.5
      IF(ITEST.LT.2) GOTO 205
      IF(IO2.GT.15) GOTO 195
      WRITE(6,101) T,L
      WRITE(6,100) (VMX(IO),IO=IO1,IO2),(RMX(IO),IO=IO1,IO2),
     1             (RINN(IO),IO=IO1,IO2),
     2            (ROUTT(IO),IO=IO1,IO2),
     3             (HWMX(IO),IO=IO1,IO2)
      WRITE(6,103) (TMX(IO),IO=IO1,IO2)
      WRITE(6,103) (TPARAP(IO),IO=IO1,IO2)
      DUM=SIG0*(2*L+1)
      DO 170 IO=IO1,IO2
 170  SIGOR(IO)=SIGOR(IO)+DUM*TMX(IO)
      GOTO 205
 195  IF(JWKB.EQ.0)
     1WRITE(6,102) VMX(IO1),RMX(IO1),HW,T,L
      IF(JWKB.EQ.1)
     1WRITE(6,202) VMX(IO1),RMX(IO1),HW,T,L,RIN,ROUT
 202  FORMAT(3F12.3,E12.3,I4,2X,'RIN,ROUT=',2F8.2)
 205  IF(T.LT..5 .AND.T1.GT.0.5)FLGRAZ=L-1
      IF(T.LT.TMIN) GOTO 260
      IF(LUP.LT.200)GOTO 210
      IF(T.LT.T00)        GOTO 260
 210  SIGML(L1)=SIG0*(2*L+1)   *T
      IF(ICLASS.EQ.1) SIGML(L1)=SIG0*(2*L+1)   *TCL
      IF(ZP.LE.0.)SIGML(L1)=SIGML(L1)*TN
      SIGF=SIGF+SIGML(L1)
 250  CONTINUE
C--------------------------------------------END L LOOP
 255  IFLAG=1
 260  LMAX=MIN0(L,LUP)
      IF(ITEST.LT.1)GOTO 999
      WRITE(6,301) ELAB,AP,ZP,AT,ZT,   V0,R0,D,Q2,CRED,NOPROX,NOCURV,
     1             ION
 301  FORMAT(/' FUSION'/' ELAB,AP,ZP,AT,ZT',F10.3,F8.0,3F6.0,4X,
     1        'V0,R0,D,Q2,CRED',5F10.3/  ' NOPROX,NOCURV,ION',3I2)
      WRITE(6,302) SIGF,LMAX,FLGRAZ,IFLAG
 302  FORMAT(' SIGFUS,LMAX,LGRAZ,FLAG',E12.3,I10,F10.0,I10/
     1      ' PARTIAL SIG')
      WRITE(6,303) (SIGML(L),L=1,LMAX)
 303  FORMAT(10E12.3)
      IF(ITEST.LT.2) GOTO 999
      IF(IO1.GT.15) GOTO 999
      WRITE(6,310)(SIGOR(IO),IO=IO1,IO2)
 310  FORMAT(/' SIGFUS FOR ORIENT.'/5E12.3/5E12.3)
      GOTO 999
C400  LMAX=0
C     FLGRAZ=0.
C     DO 410 L=1,LUP
C410  SIGML(L)=0.
C     SIGF=0.
C     WRITE(6,420) ELAB
C420  FORMAT(//F8.2,' MEV IS WELL BELOW COULOMB BARRIER,SIGFUS=0.'//)
 999  RETURN
      END