      SUBROUTINE OUT1(SPEC,N,ZERO,D,LOGUN)
C
C  Druck-Routine fuer eindimensionales Array
C  Stand: 3.5.1994
C
C     PRINTS 1-DIMENSIONAL NORMALISED ARRAY 'SPEC' OF DIMENSION 'N'
C     ALSO OUTPUTS SUM AND FIRST MOMENT
C     'ZERO' IS THE VALUE OF THE ARGUMENT FOR SPEC(1)
C     ON OUTPUT 'ZERO' IS THE FIRST MOMENT OF 'SPEC'
C     THE ARGUMENT INCREASES IN STEPS 'D'
      IMPLICIT REAL*8 (A-H,O-Z)
      DIMENSION SPEC(N),IP(10)
      SUM=0.
      FM=0.
      DO 100 I=1,N
      SUM=SUM+SPEC(I)
      FI=FLOAT(I-1)*D+ZERO
      FM=FM+FI*SPEC(I)
 100  CONTINUE
      IF(SUM.LE.0.) GOTO 150
      FM=FM/SUM
      IF(LOGUN.EQ.0) GOTO 140
      WRITE(LOGUN,105) FM,SUM
 105  FORMAT(             4X,'AVERAGE=',F8.3,4X,'SUM=',E12.3)
      FNORM=10000./SUM
      DO 120 I10=1,N,10
      E=ZERO+(I10-1)*D
      I2=MIN0(N,I10+9)
      ISUM=0
      I3=0
      DO 110 I=I10,I2
      I3=I3+1
      IP(I3)=SPEC(I)*FNORM
 110  ISUM=ISUM+IP(I3)
      IF(ISUM.LE.0) GOTO 120
      WRITE (LOGUN,130) E,(IP (I),I=1,I3 )
 120  CONTINUE
 130  FORMAT(F8.2,10I7)
 140  ZERO=FM
      RETURN
 150  ZERO=0.
      RETURN
      END