      FUNCTION VLRO(AP,AT,ZP,ZT,Q2,NORUTH,NOPROX,NOCURV,OCOS,V0,R0 ,D,
     1          XTH,APUSH,FPUSH,ECM,L,R,IOP )
C
C  Berechnet Kern-Kern-Potential, verschiedene Eingaenge V0,VL,VR
C  letzte Modifikation 29.11.1983
C  Stand: 7.6.1994
C
C  Berechnung 'Extra-Push' aus x_eq_mean = (x_cn*x_eq_eff)**0.5
C  'Gaeggler - Feldmeier - Methode, Formeln cf. z.B. GSI-85-11
C
C     2 NOV 81  CORRECTED ERROR IN CURVATURE
C     29 APR 83  INSERTED DEFAULTS COMPATIBLE WITH BLOCKI 77
C        AND CORRECTED ERROR RTS SCALING (AFFECTS OPT 1,2,4 IF Q2=0)
C     DEFORMED HI PROXIMITY POT
C     AP PROJECTILE MASS (SPHERIC)
C     AT TARGET MASS (DEFORMED)
C     ZP PROJECTILE Z  (SPHERIC)
C     ZT TARGET(DEFORMED) Z
C     Q2 QUADRUPOLE MOMENT OF TARGET IN (FM**2)
C     NORUTH #0:DOES NOT USE CHANGE OF ORIENTATION ANGLE ALONG TRAJ.
C            =2:DOES NOT USE QUADRATIC COULOMB INSIDE
C            =3:ONLY DOES COULOMB CORRECTION FOR FINITE Q2
C     NOPROX =1:USES CENTER LINE PRESCRIPTION(INSTEAD OF PROX.PRESCR.)
C     NOCURV =1:IGNORES CURVATURE DEPENDANCE OF POT
C     OCOS COS OF   ANGLE          SYM.AXIS WITH CENTER LINE AT INFINITY
C     V0,RO,D POT PARAMETRES
C     XTH,APUSH,FPUSH:PARAMETERS,XTH,A,F OF BJORNHOM-SWIATECKI 82 EXTRAP
C     ECM CENTER-OF-MASS ENERGY
C     L ORBITAL ANG.MOM.
C     R CENTER DISTANCE(FM)
C     IOPT =-1:NUCLEAR IS WS,NO RADII CORRECTION ,USE CENTRAL RADII
C     IOPT =-2:SAME AS -1 BUT FOR AP=1 SPIN ORBIT L+1/2 IS ADDED
C     IOPT =0:VNUCLEAR IS EXPONENTIAL,NO RADII CORRECTION,USE CENTRAL RA
C     IOPT =1:VNUCLEAR IS EXPONENTIAL,WITH RADII CORRECTION,USE SHARP RA
C     IOPT =2:FULL PROXIMITY POT,WITH RADII CORRECTION,USE SHARP RADII
C     IOPT =3:FULL PROXIMITY POT,NO RADII CORRECTION,USE CENTRAL RADII
C     IOPT =4: EXP PROXIMITY POT,WITH RADII CORRECTION,USE SHARP RADII
C     IOPT =5: BASS POTENTIAL,BERLIN 79, SET D=1 OR 0,USE SHARP RADII
C------------------------------------------------------------------
      IMPLICIT REAL*8 (A-H,O-Z)
      COMMON/PUSHPA/SPUSH,SCREIPA
      DATA ESQUAR,HBAR,AMU/1.4399, 0.65819D-21, 1.03641D-44/
C------------------------------------------------------------------
      IBASS=1
      IF(IOP.NE.5) IBASS=0
      IOPT=IOP
      IF(IBASS.NE.1) GOTO 5
      IOPT=4
      V0=1.
      D=1.
      NOCURV=0
C     NORUTH=1
 5    ARED=AP*AT/(AP+AT)
      EZP=ESQUAR*ZP
      COUL=EZP*ZT
      C01=ARED*AMU*COUL/HBAR
      CENT=0.5*HBAR*HBAR/(ARED*AMU)
      AP3=AP**0.333333
      AT3=AT**0.333333
      DUM=(AP+AT-2.*(ZP+ZT))/(AP+AT)
      DEPI= 1.-1.7826*DUM*DUM
C
      EXPUSH=0.
      IF(XTH.LE.0.) GOTO 7
      ZETACR=50.883*DEPI
      DEPA=AP3*AT3*(AP3+AT3)
      IF(SPUSH.GT.0) GOTO 6
      ZETA=4.*ZP*ZT/DEPA-ZETACR*XTH
      PUSHK=7.601E-4*DEPA*(AP3+AT3)*APUSH*APUSH/(AP+AT)
      IF(ZETA.GT.0.) EXPUSH=PUSHK*ZETA*ZETA
      GOTO 8
 6    AMAPA=DEPA*(AP+AT)*(AP+AT)
      ZETAF=4*AP*AT*(ZP+ZT)*(ZP+ZT)/AMAPA
      ZSPALT=(ZP+ZT)*(ZP+ZT)/(AP+AT)
      ZETFM=SQRT(ZETAF*ZSPALT)
      ZETA=ZETFM-ZETACR*XTH
      PUSHK=7.601E-4*DEPA*(AP3+AT3)*APUSH*APUSH/(AP+AT)
      IF(ZETA.GT.0.) EXPUSH=PUSHK*ZETA*ZETA
      IF(SCREIPA.GT.0.) GOTO 8
      SCREIPA=1
      XEQEFF=ZETAF/ZETACR
      XCN=ZSPALT/ZETACR
      XEQM=ZETFM/ZETACR
      ECHPU=7.601E-4*DEPA*(AP3+AT3)*ZETACR*ZETACR/(AP+AT)
      WRITE(6,1001)EXPUSH,XEQM,XTH,APUSH,ECHPU,XCN,XEQEFF
 1001 FORMAT(/'Extra-Push Parameter: E_push =',F8.2,' MeV',3X,
     a'x_eq_m=',F6.3,3x,'xth=',F6.3,3x,'Apush=',F6.3,3X,'E_ch=',
     bF8.3,3X,'xcn=',F6.3,3X,'x_eq_eff=',F6.3)
 8    ALCH=0.10270*DEPA*AP3*AT3/SQRT(AP+AT)
      FLCH=FPUSH/ALCH
      FLCH2=FLCH*FLCH
 7    IF(XTH.LT.0.) EXPUSH=APUSH
C
      IF(V0.GT.0.) GOTO 9
      DUM=0.9517*DEPI
      IF(IOPT.GT.1)V0=12.5664   *DUM
      IF(IOPT.EQ.0 .OR. IOPT.EQ.1 ) V0=43.1906*DUM
 9    IF(IOPT.GT.1 .AND. D.LE.0.) D=1.
      IF(IOPT.LT.2 .AND. D.LE.0.) D=0.75
      RTS=R0*AT3
      RPS=R0*AP3
      IF(AP.LT.4.01 .AND. AP.GT.3.99) RPS=1.6
      IF(RTS.GT.0.) GOTO 10
      RPS=1.28*AP3-0.76+0.8/AP3
      RTS=1.28*AT3-0.76+0.8/AT3
      IF(IOPT.EQ. 1 .OR.IOPT.EQ.2 .OR. IOPT.EQ.4) GOTO 9000
      RPS=RPS- 1./RPS
      RTS=RTS- 1./RTS
 9000 R0=(RPS+RTS)/(AP3+AT3)
 10   RA=RTS
      RC=RTS
      RBAR=RTS*RPS/(RTS+RPS)
      Q2A=0.
      Q4A=0.
      IF(ABS(Q2).LT.0.01) GOTO 25
      RTQ=1.15*AT3
      Q2A=0.5*Q2
      VQ20=EZP*Q2A
      IF(NORUTH.EQ.3) GOTO 25
C-------------------------------
C     AXES OF ELLIPSOID
      DUM=2.5*Q2/ZT
      RQ3=RTQ*RTQ*RTQ
      RC0=RTQ
      IREP=0
 15   RC1=DUM+RQ3/RC0
      RC1=SQRT(RC1)
      DIFF=RC1-RC0
      IF(ABS(RC1-RC0).LT.0.01) GOTO 18
      IREP=IREP+1
      IF(IREP.GT.20) GOTO 18
      RC0=RC1
      GOTO 15
 18   RC=0.5*(RC1+RC0)
      RA=SQRT(RQ3/RC)
      RC=RTS*RC/RTQ
      RA=RTS*RA/RTQ
 25   IF(IOPT.LE.0) GOTO 26
      IF(IOPT.EQ.4) GOTO 28
      IF(IOPT.GT.2) GOTO 26
C     RADII CORRECTION FOR IOPT=1,2,4
 28   DSQ=D*D
      RPS=RPS-DSQ/RPS
      RTS=RTS-DSQ/RTS
      RA=RA-DSQ/RC
      RC=RC-DSQ*RC/(RA*RA)
 26   RA2=RA*RA
      RELL2=RA2
      RELL=RA
      RC2=RC*RC
      EPS2=(RC2-RA2)/RC2
      EPS3=EPS2*0.5/RA2
 30   CONTINUE
C-------------------------------------------------
C      ENTRY VO(L,R,ECM,OCOS)
      IF(ABS(Q2).LT.0.01) GOTO 40
      IF(OCOS.NE.OCOS1)PHI=ACOS(OCOS)
      OCOS1=OCOS
      IF(NORUTH.EQ.0) GOTO 40
      PHIR=PHI
      X=OCOS
      SINR=SIN(PHIR)
      X2=X*X
      P2=1.5*X2-0.5
      VQ2=VQ20*P2
      IF(Q4A.EQ.0.) GOTO 40
      P4=4.3750*X2*X2-3.75*X2+0.375
      VQ4=EZP*Q4A*P4
 40   CONTINUE
C---------------------------------------------------
C     ENTRY VL(L,R,ECM,OCOS)
      AL=L
      AL2=AL*(AL+1.)
      CENTL=CENT*AL2
C
      EXPUSH=0.
      IF(XTH.LE.0.) GOTO 50
      DUM=ZETA+FLCH2*AL2
      IF(DUM.GT.0.) EXPUSH=PUSHK*DUM*DUM
 50   IF(XTH.LT.0.) EXPUSH=APUSH
C
      IF(ABS(Q2).LT.0.01) GOTO 150
      IF(OCOS.NE.OCOS1)PHI=ACOS(OCOS)
      OCOS1=OCOS
      IF(NORUTH.NE.0) GOTO 150
      CHIAS=0.
      IF(L.EQ.0) GOTO  80
      C02=2.*ARED*AMU*ECM
      C01L=C01/AL
      C03L=SQRT(C02+C01L*C01L)
      DUM2=C01L/C03L
      CHIAS=ACOS(DUM2)
 80   PHIR=PHI-CHIAS
      X=COS(PHIR)
      SINR=SIN(PHIR)
      X2=X*X
      P2=1.5*X2-0.5
      VQ2=VQ20*P2
      IF(Q4A.EQ.0.) GOTO 150
      P4=4.3750*X2*X2-3.75*X2+0.375
      VQ4=EZP*Q4A*P4
C----------------------------------------------------
C      ENTRY VR(R)
C
 150  R2=R*R
      VCENT=CENTL/R2
      VCOUL=COUL/R
      IF(ABS(Q2) .LT.0.01) GOTO 280
      R3=R2*R
      VCOUL=VCOUL+VQ2/R3
      IF(Q4A.EQ.0.) GOTO 200
      R5=R3*R2
      VCOUL=VCOUL+VQ4/R5
C
 200  IF(ABS(Q2).LT.0.01 .OR. NORUTH.EQ.3) GOTO 280
      PHIMIN=PHIR
      COSMIN=X
      IREP=0
      IF(NOPROX.EQ.0) GOTO 220
C--------------------------------------------------------
C     GET MIN.DIST. 'S0' AND ANGLE 'PHIMIN'
      RELL2=RA2/(1.-EPS2*X2)
      RELL=SQRT(RELL2)
      GOTO 230
 225  COSMIN=COS(PHIMIN)
 220  DUM2=COSMIN*COSMIN
      RELL2=RA2/(1.-EPS2*DUM2)
      RELL=SQRT(RELL2)
      IREP=IREP+1
      IF(IREP.EQ.2) GOTO 230
      DUM=2.*PHIMIN
      DELTA=(R-RELL)*RELL2*SIN(DUM)*EPS3/R
      IF(ABS(DELTA).GT.ABS(PHIR))DELTA=0.
      PHIMIN=PHIR-DELTA
      GOTO 225
 230  XELL=RELL*COSMIN
      YELL=RELL*SIN(PHIMIN)
      DUM=R*X        -XELL
      DU1=R*SINR     -YELL
      S0=SQRT(DUM*DUM+DU1*DU1)-RPS
      GOTO 290
 280  S0=R-RPS-RTS
 290  IF(NORUTH.EQ.2)GOTO 291
      RTOUCH=RELL+RPS
      IF(S0.LT.0.)VCOUL=VCOUL-COUL/R +1.5*COUL*(1.-0.333333*(R/RTOUCH)**
     1 2.)/RTOUCH
 291  IF(NOCURV.EQ.1) GOTO 310
C---------------------------------------------------
C     GET REDUCED CURVATURE  ELLIPSOID(RC,RA) + SPHERE(RPS)
      IF(ABS(Q2).LE.0.01 .OR. NORUTH.EQ.3) GOTO 305
      COS2V=(RELL2-RA2)/(RC2-RA2)
      SIN2V=1.-COS2V
      DUM=RA2*COS2V+RC2*SIN2V
      DUM=ABS(DUM)
      R1R2=DUM*DUM/RC2
      R1PR2=(RA2+DUM)*SQRT(DUM)/(RA*RC)
      GOTO 306
 305  R1R2=RTS*RTS
      R1PR2=RTS+RTS
 306  RBAR2=R1R2*RPS*RPS/(R1R2+RPS*R1PR2+RPS*RPS)
      RBAR=SQRT(RBAR2)
      GOTO 320
 310  RBAR=1.
C------------------------------------------------------
 320  IF(IOPT.LT.2) GOTO 325
      ZETA=S0/D
      IF(IOPT.EQ.4) GOTO 321
      IF(ZETA.LT.1.2511)GOTO 322
 321  IF(IBASS.EQ.0) PHIFU=-3.437*EXP(-ZETA/0.75)
      IF(IBASS.EQ.1) PHIFU=-1./(.033*EXP(ZETA/3.5)+0.007*EXP(ZETA/.65))
      GOTO 323
 322  DUM=ZETA-2.54
      DUM2=DUM*DUM
      PHIFU=-0.5*DUM2-0.0852*DUM*DUM2
 323  VN=V0*D*RBAR*PHIFU
      GOTO 328
 325  IF(IOPT.EQ.(-1))GOTO 335
      IF(IOPT.EQ.(-2))GOTO 335
      DUM=S0/D
      VN=0.
      IF(DUM.LT.150.) VN=-V0*RBAR*EXP(-DUM)
 328  VLRO=VCOUL+VCENT+VN+EXPUSH
      RETURN
 335  DUM=S0/D
      VN=0.
      IF(DUM.LT.150.) VN=-V0*RBAR/(1.+EXP(DUM))
      IF(IOPT.NE.(-2)) GOTO 328
C     FOR TEST PURPOSE ADD SPIN ORBIT FOR PROTONS J=L+1/2
C     BECCHETTI 1969
      IF(AP.GT.1.01) GOTO 328
      DUM=(R-1.01*AT**(1./3))/0.75
      VSO=0.
      IF(DUM.LT.80.) DUM1=1.+EXP(DUM)
      IF(DUM.LT.80.) VSO=-6.2*AL*2.0*EXP(DUM)/(0.75*R*DUM1*DUM1)
      VN=VN+VSO
      GOTO 328
      END